steps:
    - id: "Performing docker-compose"
      name: 'docker/compose'
      args: ["-f", "docker-compose.prod.yml", "up", "-d"]

    - id: "Chown in /var/www"
      name: 'docker'
      args: ['exec','-u','root','-t','micro-videos-app','chown','-R','www-data:www-data','/var/www']

    - id: "Performing composer"
      name: 'docker'
      args: ["exec", "-t", "micro-videos-app", "composer", "install"]

    - id: "Copying .env"
      name: 'docker'
      args: ["exec", "-t", "micro-videos-app", "cp", ".env.example", ".env"]

    - id: "Copying .env.testing"
      name: 'docker'
      args: ["exec", "-t", "micro-videos-app", "cp", ".env.testing.example", ".env.testing"]

    - id: "Performing key:generate"
      name: 'docker'
      args: ["exec", "-t", "micro-videos-app", "php", "/var/www/artisan", "key:generate"]

    - id: "Performing migrations"
      name: 'docker'
      args: ["exec", "-t", "micro-videos-app", "php", "/var/www/artisan", "migrate"]

    - id: "Performing PHPUnit"
      name: 'docker'
      args: ["exec", "-t", "micro-videos-app", "php", "/var/www/vendor/bin/phpunit", "-c","/var/www/phpunit.xml"]
