version: '3'

services:
    laravel-app:
        build: .
        container_name: laravel-app
        volumes:
            - .:/var/www
        depends_on:
            - laravel-db
            - laravel-redis
        networks:
            - laravel-network

    laravel-nginx:
        build: .docker/nginx
        container_name: laravel-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        depends_on:
            - laravel-app
        networks:
            - laravel-network

    laravel-db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: laravel-db
        restart: always
        tty: true
        ports:
            - "3307:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - laravel-network

    laravel-redis:
        image: redis:alpine
        container_name: laravel-redis
        ports:
            - "6379:6379"
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
